#!/usr/bin/env bash
# simplified brew.sh install CLT procedure

should_install() {
  local dev
  local ver=$(sw_vers -productVersion | sed -n -E 's/^([0-9]+)\.([0-9]+)[0-9.-]*/\1.\2/p')
  local max=$(echo $ver | sed -n -E 's/^([0-9]+)\.([0-9]+)/\1/p')
  local min=$(echo $ver | sed -n -E 's/^([0-9]+)\.([0-9]+)/\2/p')
  if [ "$(echo $max'>=10' | bc -l)" = "1" ] && [ "$(echo $min'>9' | bc -l)" = "1" ]; then
    dev=$(xcode-select -print-path)
    if [ "$(ls $dev)" = "" ] || [ ! -f "${dev}/usr/bin/git" ]; then
      echo true
    fi
  fi
}

if [ "$(should_install)" = "true" ]; then
  touch /tmp/.com.apple.dt.CommandLineTools.installondemand.in-progress
  label=$(softwareupdate -l | grep -B 1 -E "Command Line (Developer|Tools)" | awk -F"*" '/^ +\\*/ {print $2}' | sed 's/^ *//' | head -n1)
  echo "installing ${label}"
  softwareupdate -i $label
  rm -f /tmp/.com.apple.dt.CommandLineTools.installondemand.in-progress
  # fallback to the old way in case
  # it still needs to be installed
  if [ "$(should_install)" = "true" ]; then
    echo "Installing the Command Line Tools (expect a GUI popup)"
    xcode-select --install
    echo "Please remember to accept the license"
    echo "  sudo xcodebuild -license"
  fi
else
  echo 'nothing to do'
fi
