#!/usr/bin/env bash
# simplified brew.sh install CLT procedure

should_install() {
  local dev
  local ver=$(sw_vers -productVersion | sed -n -E 's/^([0-9]+)\.([0-9]+)[0-9.-]*/\1.\2/p')
  local max=$(echo $ver | sed -n -E 's/^([0-9]+).([0-9]+)/\1/p')
  local min=$(echo $ver | sed -n -E 's/^([0-9]+).([0-9]+)/\2/p')
  if [ "$(echo $max'>=10' | bc -l)" = "1" ] && [ "$(echo $min'>9') | bc -l" = "1" ]; then
    dev=$(xcode-select -print-path)
    if [ "$(ls $dev)" = "" ] || [ ! -f "${dev}/usr/bin/git" ]; then
      echo true
    fi
  fi
}

if [ "$(should_install)" = "true" ]; then
  touch /tmp/.com.apple.dt.CommandLineTools.installondemand.in-progress
  softwareupdate -i $(softwareupdate -l | grep -B 1 -E "Command Line (Developer|Tools)" | awk -F"*" '/^ +\\*/ {print $2}' | sed 's/^ *//' | head -n1)
  rm -f /tmp/.com.apple.dt.CommandLineTools.installondemand.in-progress
fi

if [ "$(should_install)" = "true" ]; then
  xcode-select --install
fi
