#!/usr/bin/env bash
# simplified brew.sh install CLT procedure

should_install() {
  local dev
  local ver=$(sw_vers -productVersion | sed -n -E 's/^([0-9]+)\.([0-9]+)[0-9.-]*/\1.\2/p')
  local max=echo $ver | sed -e 's/^([0-9]+).([0-9]+)/\1/'
  local min=echo $ver | sed -e 's/^([0-9]+).([0-9]+)/\2/'
  if [ 10 -lte $max ] && [ 9 -lt $min ]; then
    dev=$(xcode-select -print-path)
    if [ "$(ls $dev)" = "" ] || [ ! -f "${dev}/usr/bin/git" ]; then
      echo true
    fi
  fi
}

if [ "$(should_install)" = "true" ]; then
  touch /tmp/.com.apple.dt.CommandLineTools.installondemand.in-progress
  softwareupdate -i $(softwareupdate -l | grep -B 1 -E "Command Line (Developer|Tools)" | awk -F"*" '/^ +\\*/ {print $2}' | sed 's/^ *//' | head -n1)
  rm -f /tmp/.com.apple.dt.CommandLineTools.installondemand.in-progress
fi

if [ "$(should_install)" = "true" ]; then
  xcode-select --install
fi
