#!/usr/bin/env sh
imports=imports// "exec" "gjs" "-I" "$(dirname $0)" "$0" "$@"
imports.jsgtk.env;

const GLib = imports.gi.GLib;

let
  utils = imports.jsgtk.env._,
  Class = utils.Class,
  child_process = require('child_process'),
  fs = require('fs'),
  os = require('os'),
  path = require('path'),
  counter = 0,
  t = 0,
  async = function (cb) {
    if (t) clearTimeout(t);
    t = 0;
    counter++;
    return function () {
      let result = cb.apply(this, arguments);
      counter--;
      if (counter === 0) t = setTimeout(process.exit, 500);
    };
  }
;

process.run(function () {

  require('holdon');

  console.assert(screen.width > 0 && screen.height > 0,
    'global.screen is correctly defined');


  console.assert(System.global === Function('return this')(),
    'System.global is correctly defined');

  console.assert(path.extname('.git') === '',
    'a file name starting with dot does not count as extension');
  console.assert(path.extname('a.git') === '.git',
    'path.extname works as expected');
  console.assert(path.isAbsolute('/home'),
    'path.isAbsolute works as expected');
  console.assert(!path.isAbsolute('home'),
    'path.isAbsolute still works as expected');
  console.assert(path.normalize('/foo/bar//baz/./asdf/quux/..') === '/foo/bar/baz/asdf',
    'path.normalize works as expected');
  console.assert(path.normalize('/foo/bar//baz/./asdf/') === '/foo/bar/baz/asdf/',
    'path.normalize works again as expected');
  console.assert(path.join('/foo', 'bar', 'baz/asdf', 'quux', '..') === '/foo/bar/baz/asdf',
    'path.join works as expected');
  console.assert(path.resolve('foo/bar', '/tmp/file/', '..', 'a/../subfile') === '/tmp/subfile',
    'path.resolve works as expected');

  console.assert(require('./module').method() === 'module works',
    'require in same folder works as expected');
  console.assert(require('./node_modules/another/main').method() === 'node_modules works',
    'require in sub folders works as expected too');

  console.assert(require('/home/webreflection/code/jsgtk/module').method() === 'module works',
    'require in absoulte folder works as expected');
  console.assert(require('/home/webreflection/code/jsgtk/node_modules/another/main').method() === 'node_modules works',
    'require in sub absoulte folders works as expected too');

  console.assert(fs.readFileSync('./test') == GLib.file_get_contents('./test')[1],
    'fs.readFileSync works as expected too');

  fs.readFile('./test', async(function (err, data) {
    console.assert(data == GLib.file_get_contents('./test')[1], 'fs.readFile works as expected');
    if (err) {
      console.error(err.message);
    }
  }));


  let tmp = Math.random();
  fs.writeFileSync('./test.txt', tmp);
  console.assert(fs.readFileSync('./test.txt') == tmp,
    'fs.writeFileSync works as expected');

  (function (tmp) {
    fs.writeFile('./test.txt', tmp, async(function (err) {
      console.assert(fs.readFileSync('./test.txt') == tmp, 'fs.writeFile works as expected');
      if (err) {
        console.error(err.message);
      }

      child_process.execSync('rm test.txt');

      let syncData = child_process.spawnSync('ls', ['-lah']).stdout.toString();
      console.assert(syncData.length > 0,
        'child_process.spawnSync works as expected');

      console.assert(!/test\.txt/.test(syncData), 'execSync worked as expected');

      let cp = child_process.spawn('ls', ['-lah']);
      let content = '';
      cp.stdout.on('data', (data) => content += data);
      cp.on('close', async((code) => {
        console.assert(code === 0, 'spawn exited with the right code');
        console.assert(content === syncData, 'spawn collected the right data');
      }));

    }));

  }(Math.random()));


  let A = Class({
    name: 'a',
    method: function () {
      return this.name;
    }
  });
  let B = Class({
    extends: A,
    static: {
      B: true
    },
    name: 'b'
  });

  console.assert((new B).name === 'b', 'Class#extends work as expected');
  console.assert((new B) instanceof B && (new A) instanceof A && (new B) instanceof A,
    'Class inheritance work as expected');
  console.assert(B.B === true, 'Class#static work as expected');

  A = Class({
    constructor: function () {
      this.a = true;
    }
  });
  B = Class({
    extends: A,
    constructor: function () {
      this.b = true;
    }
  });
  console.assert((new B).a === true && (new B).b === true,
    'Class parent invoke works as expected');

});