#!/usr/bin/env bash

# example
# ./utils/compare tests/runtime.js

DIR=$(pwd)
if [ "${DIR:${#DIR}-6}" == "/utils" ]; then
  DIR="${DIR}/.."
fi

echo ""
echo -e "$(tput bold)# NodeJS ########################################$(tput sgr0)"
time node $@

echo ""
echo -e "$(tput bold)# JSGtk #########################################$(tput sgr0)"
time ${DIR}/jsgtk $@
echo ""