#!/usr/bin/env bash

DIR=$(pwd)
if [ "${DIR:${#DIR}-6}" == "/utils" ]; then
  DIR="${DIR}/.."
fi

jshintDir() {
  echo -e "$2$(tput bold)$1/*$(tput sgr0)"
  for file in $(ls $1); do
    if [ -d $1/$file ]; then
      jshintDir $1/$file "$2$2"
    else
      echo "$2  └─  $1/$file"
      ${DIR}/node_modules/.bin/jshint $1/$file
    fi
  done
}

echo ''
echo -e "$(tput bold)jshint$(tput sgr0)"
echo "  └─  jsgtk"
${DIR}/node_modules/.bin/jshint $DIR/jsgtk
jshintDir $DIR/jsgtk_modules '  '
echo ''