#!/usr/bin/env bash

DIR=$(pwd)
if [ "${DIR:${#DIR}-6}" == "/utils" ]; then
  DIR="${DIR}/.."
fi

jshintDir() {
  echo -e "$2$(tput bold)$1/*$(tput sgr0)"
  for file in $(ls $1); do
    if [ -d $1/$file ]; then
      jshintDir $1/$file "$2$2"
    else
      if [ "$file" != "babel.js" ]; then
        echo "$2  └─  $1/$file"
        ${DIR}/node_modules/.bin/jshint $1/$file
      fi
    fi
  done
}

echo ''
echo -e "$(tput bold)jshint$(tput sgr0)"
echo "  └─  jsgtk"
cat $DIR/jsgtk > /tmp/jsgtk
sed -i "s/Function=.*//" /tmp/jsgtk
${DIR}/node_modules/.bin/jshint /tmp/jsgtk
rm /tmp/jsgtk
jshintDir $DIR/jsgtk_modules '  '
echo ''